// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEgXwiFkQi866abxuE7IZB51wylzGZ-Dk',
    appId: '1:355544304131:web:7cf6d0608f6d8ecb3adc36',
    messagingSenderId: '355544304131',
    projectId: 'lavenz-d7f47',
    authDomain: 'lavenz-d7f47.firebaseapp.com',
    storageBucket: 'lavenz-d7f47.appspot.com',
    measurementId: 'G-J3H1X5YF9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoS_6NnhJb_F4Le81lfIolvCGzAMRnJOA',
    appId: '1:355544304131:android:ae1c219190ed3d563adc36',
    messagingSenderId: '355544304131',
    projectId: 'lavenz-d7f47',
    storageBucket: 'lavenz-d7f47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV6rnJLjY2soJCqIPDaJzTkBg55R6dI8o',
    appId: '1:355544304131:ios:cbde269fe8b7e85d3adc36',
    messagingSenderId: '355544304131',
    projectId: 'lavenz-d7f47',
    storageBucket: 'lavenz-d7f47.appspot.com',
    iosClientId: '355544304131-e0i4tju7cbq41dgkdpitgekvs8amj4lu.apps.googleusercontent.com',
    iosBundleId: 'com.vqh2602.lavenz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV6rnJLjY2soJCqIPDaJzTkBg55R6dI8o',
    appId: '1:355544304131:ios:cbde269fe8b7e85d3adc36',
    messagingSenderId: '355544304131',
    projectId: 'lavenz-d7f47',
    storageBucket: 'lavenz-d7f47.appspot.com',
    iosClientId: '355544304131-e0i4tju7cbq41dgkdpitgekvs8amj4lu.apps.googleusercontent.com',
    iosBundleId: 'com.vqh2602.lavenz',
  );
}
